/* ************************************************************************** */
/** Descriptive File Name

  @Company
    Smart Slug Bin

  @File Name
    TopSM.h

  @Summary
 Contains the top level state machine of Smart Slug Bin

  @Description
 The Top level of Smart Slug Bin consists of 3 states that are changed by a User 
 Event , generated by the proximity sensor, an Item Event generated by an IR
 Sensor or Load Cell, or a Timeout Event. The 3 States are IDLE, WAIT, and 
 ACTIVE. In active the state machine will enter the sub-state machine, wmSM (Waste
 Management State Machine).
 * 
 */
/* ************************************************************************** */
#include "TopSM.h"
#include "wmSM.h"
#include "lmrSM.h"

/** 
  @Function
    void runTopSM(void);

  @Summary
    This is the top level of the state machine.

  @Remarks
    Refer to the TopSM.h header for function usage details.
 */
SSB runlmrSM(SSB lmr)
{
    switch (lmr.lmrState) {
    case LMRINIT:
        lmr.lmrState = FORWARD;
        lmr.lmrtime = lmr.globalTime;
        updateOLEDLMR(lmr);
        break;
    case FORWARD:
        if (lmr.item == ALUMINUM && (lmr.globalTime - lmr.lmrtime > BIN_1)) {
            lmr.lmrState = DROP;
            lmr.lmrtime = lmr.globalTime;
            updateOLEDLMR(lmr);
        } else if (lmr.item == GLASS && (lmr.globalTime - lmr.lmrtime > BIN_2)) {
            lmr.lmrState = DROP;
            lmr.lmrtime = lmr.globalTime;
            updateOLEDLMR(lmr);
        } else if (lmr.item == PLASTIC && (lmr.globalTime - lmr.lmrtime > BIN_3)) {
            lmr.lmrState = DROP;
            lmr.lmrtime = lmr.globalTime;
            updateOLEDLMR(lmr);
        }
        break;
    case DROP:
        if (lmr.globalTime - lmr.lmrtime > DROP_TIMEOUT) {
            lmr.lmrState = REVERSE;
            updateOLEDLMR(lmr);
        }
        break;
    case REVERSE:
        if (lmr.item == ALUMINUM && (lmr.globalTime - lmr.lmrtime > BIN_1)) {
            lmr.lmrState = LMRINIT;
            lmr.wmState = WMINIT;
            lmr.event = NO_ITEM;
        } else if (lmr.item == GLASS && (lmr.globalTime - lmr.lmrtime > BIN_2)) {
            lmr.lmrState = LMRINIT;
            lmr.wmState = WMINIT;
            lmr.event = NO_ITEM;
        } else if (lmr.item == PLASTIC && (lmr.globalTime - lmr.lmrtime > BIN_3)) {
            lmr.lmrState = LMRINIT;
            lmr.wmState = WMINIT;
            lmr.event = NO_ITEM;
        }
        break;
    default:
        break;
    }
    return lmr;
}

/** 
  @Function
    SSB updateOLEDTop(SSB lmr);

  @Summary
    

  @Remarks
    
 */
void updateOLEDLMR(SSB lmr)
{
    switch (lmr.lmrState) {
    case FORWARD:
        sprintf(display, "LMR Level\nState: FORWARD\n");
        OledClear(OLED_COLOR_BLACK); // clears the OLED to remove any lingering characters from previous prints
        OledDrawString(display);
        OledUpdate(); // prints the new string
        break;
    case DROP:
        sprintf(display, "LMR Level\nState: DROP");
        OledClear(OLED_COLOR_BLACK); // Removes any lingering characters
        OledDrawString(display);
        OledUpdate(); // Prints the new OLED display
        break;
    case REVERSE: //
        sprintf(display, "LMR Level\nState: REVERSE");
        OledClear(OLED_COLOR_BLACK); // Removes any lingering characters
        OledDrawString(display);
        OledUpdate(); // Prints the new OLED display
        break;
    }
}


/* *****************************************************************************
 End of File
 */
