/* ************************************************************************** */
/** Descriptive File Name

  @Company
    Smart Slug Bin

  @File Name
    TopSM.h

  @Summary
 Contains the top level state machine of Smart Slug Bin

  @Description
 The Top level of Smart Slug Bin consists of 3 states that are changed by a User 
 Event , generated by the proximity sensor, an Item Event generated by an IR
 Sensor or Load Cell, or a Timeout Event. The 3 States are IDLE, WAIT, and 
 ACTIVE. In active the state machine will enter the sub-state machine, wmSM (Waste
 Management State Machine).
 * 
 */
/* ************************************************************************** */
#include "TopSM.h"
#include "wmSM.h"
#include "lmrSM.h"

/** 
  @Function
    void runTopSM(void);

  @Summary
    This is the top level of the state machine.

  @Remarks
    Refer to the TopSM.h header for function usage details.
 */
SSB runTopSM(SSB top)
{
    switch (top.topState) {
    case TOPINIT:
        top.topState = IDLE;
        updateOLEDTop(top);
        break;
    case IDLE:
        if (top.button == BUTTON_EVENT_4DOWN) {
            top.topState = WAIT;
            top.waitTimeStart = top.globalTime;
            top.button = BUTTON_EVENT_NONE;
        }
        updateOLEDTop(top);
        break;
    case WAIT:
        if (top.globalTime - top.waitTimeStart == WAIT_TIMEOUT) {
            top.topState = IDLE;
            updateOLEDTop(top);
        } else if (top.button == BUTTON_EVENT_3DOWN) {
            top.topState = ACTIVE;
            top.button = BUTTON_EVENT_NONE;
        }
        break;
    case ACTIVE:
        if (top.event == NO_ITEM) {
            top.topState = WAIT;
            top.event = FALSE;
            top.waitTimeStart = top.globalTime;
            updateOLEDTop(top);
        }
        else {
            top = runwmSM(top);
        }
        break;
    default:
        break;
    }
    return top;
}

/** 
  @Function
    SSB updateOLEDTop(SSB top);

  @Summary
    

  @Remarks
    
 */
void updateOLEDTop(SSB top)
{
    switch (top.topState) {
    case IDLE:
        sprintf(display, "Top Level\nState: IDLE");
        OledClear(OLED_COLOR_BLACK); // clears the OLED to remove any lingering characters from previous prints
        OledDrawString(display);
        OledUpdate(); // prints the new string
        break;
    case WAIT: //
        sprintf(display, "Top Level\nState: WAITING");
        OledClear(OLED_COLOR_BLACK); // Removes any lingering characters
        OledDrawString(display);
        OledUpdate(); // Prints the new OLED display
        break;
    case ACTIVE: // 
        sprintf(display, "Top Level\nState: ACTIVE");
        OledClear(OLED_COLOR_BLACK); //Removes any lingering characters
        OledDrawString(display);
        OledUpdate(); // Prints the new OLED display
        break;
    }
}


/* *****************************************************************************
 End of File
 */
