/* ************************************************************************** */
/** Descriptive File Name

  @Company
    Smart Slug Bin

  @File Name
    TopSM.h

  @Summary
 Contains the top level state machine of Smart Slug Bin

  @Description
 The Top level of Smart Slug Bin consists of 3 states that are changed by a User 
 Event , generated by the proximity sensor, an Item Event generated by an IR
 Sensor or Load Cell, or a Timeout Event. The 3 States are IDLE, WAIT, and 
 ACTIVE. In active the state machine will enter the sub-state machine, wmSM (Waste
 Management State Machine).
 * 
 */
/* ************************************************************************** */
//#iclude "main.c"
#include "configure.h"
#ifndef _TOPSM_H    /* Guard against multiple inclusion */
#define _TOPSM_H

    /**
      @Function
        void runTopSM(void);

      @Summary
        This is the top level of the state machine.

      @Description
     The top level runs through 3 states: IDLE | WAIT | ACTIVE
        <p>
     IDLE: The bin will be operating at minimal power in order to conserve 
           energy. The bin will transition into WAIT if an ssb.userEvent happens
           from the proximity sensor.
        <p>
     WAIT: The bin has been activated by a ssb.userEvent which will cause the
           bin to power up and in preparation for an ssb.itemEvent. The bin will
           return to IDLE if it times out. An ssb.itemEvent will transition the
           the bin into ACTIVE.
        <p>
     ACTIVE: The bin will enter wmSM upon transition from WAIT state. Bin will
           transition back into WAIT after the ssb.item has been consumed by 
           trashing or recycling the item.
     */
    SSB runTopSM(SSB top);
    
    void updateOLEDTop(SSB top);
#endif /* _TOPSM_H */

/* *****************************************************************************
 End of File
 */
