/* ************************************************************************** */
/** Descriptive File Name

  @Company
    Smart Slug Bin

  @File Name
    TopSM.h

  @Summary
 Contains the top level state machine of Smart Slug Bin

  @Description
 The Top level of Smart Slug Bin consists of 3 states that are changed by a User 
 Event , generated by the proximity sensor, an Item Event generated by an IR
 Sensor or Load Cell, or a Timeout Event. The 3 States are IDLE, WAIT, and 
 ACTIVE. In active the state machine will enter the sub-state machine, wmSM (Waste
 Management State Machine).
 * 
 */
/* ************************************************************************** */

#include "TopSM.h"
/** 
  @Function
    void runTopSM(void);

  @Summary
    This is the top level of the state machine.

  @Remarks
    Refer to the TopSM.h header for function usage details.
 */
SSB runTopSM(SSB ssb)
{
    switch (ssb.topState) {
    case TOPINIT:
        ssb.topState=IDLE;
        updateOLEDTop(ssb);
        break;
    case IDLE:
        if (ssb.button == BUTTON_EVENT_4DOWN) {
            ssb.topState = WAIT;
            ssb.waitTimeStart = ssb.globalTime;
            ssb.button = BUTTON_EVENT_NONE;
        }
        updateOLEDTop(ssb);
        break;
    case WAIT:
        if (ssb.globalTime - ssb.waitTimeStart == WAIT_TIMEOUT) {
            ssb.topState = IDLE;
            updateOLEDTop(ssb);
        } else if (ssb.button == BUTTON_EVENT_3DOWN) {
            ssb.topState = ACTIVE;
            ssb.button = BUTTON_EVENT_NONE;
//            updateOLEDTop(top);
        }
        break;
    case ACTIVE:
        if (ssb.event == NO_ITEM) {
            updateOLEDTop(ssb);
            ssb.topState = WAIT;
            ssb.event=FALSE;
            ssb.waitTimeStart = ssb.globalTime;
        }
//        ssb.button = FALSE;
//        ssb.wmState=WMINIT;
//        ssb.buttonpress = top.globalTime;
        //        else if(ssb.item)
//                updateOLEDTop(ssb);
//        if(ssb.button){
            runwmSm();
        
        break;
    }
}


/* *****************************************************************************
 End of File
 */
